spring.application.name=005-poduct-search-Redis1

spring.datasource.url=jdbc:mysql://localhost:3306/5th_jan_2026_batch
spring.datasource.username=root
spring.datasource.password=Root@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



spring.data.redis.host=striking-mudfish-170159.upstash.io
spring.data.redis.port=6379
spring.data.redis.password=gQAAAAAAApivAAIgcDIwMmRjOTM1YzllYWQ0ODdkODk1YmFlZWQ3NzhiNDY3NQ
spring.data.redis.ssl.enabled=true

spring.cache.type=redis

# OPTIONAL LOGS
logging.level.org.springframework.cache=TRACE
logging.level.org.springframework.data.redis=DEBUG