spring.application.name=004-AmazonProductService-mongoDB

server.port=8083

spring.data.mongodb.uri=mongodb+srv://developmentsearchinto_db_user:l95fXVvGfyHJXVLX@mycluster1.0u6tpl8.mongodb.net/AmazonProduct?appName=MyCluster1