spring:
  application:
    name: 003-payment-service

  # Database Connection
  datasource:
    url: jdbc:mysql://localhost:3306/5th_jan_2026_batch
    username: root
    password: Root@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hibernate Properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

# Server Port
# server:
#   port: 8081

# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
